### ISSUE TITLE
'GPT2Config' object has no attribute '_AutoTokenizer__class'

### ISSUE THREAD

**Issue by Yumeka999** [raynardj/yuan#1]
PRETRAINED = r"wenyanwen-chinese-translate-to-ancient"
tokenizer = AutoTokenizer.from_pretrained(PRETRAINED)
model = EncoderDecoderModel.from_pretrained(PRETRAINED)

运行上述代码直接报错

请问transformers运行哪个版本

**Comment by Yumeka999** [comment]
执行tokenizer = AutoTokenizer.from_pretrained(PRETRAINED)报错

**Comment by raynardj** [comment]
> PRETRAINED = r"wenyanwen-chinese-translate-to-ancient" tokenizer = AutoTokenizer.from_pretrained(PRETRAINED) model = EncoderDecoderModel.from_pretrained(PRETRAINED)
> 
> 运行上述代码直接报错
> 
> 请问transformers运行哪个版本

不好意思， 刚看到。

目前这个模型被部署在huggingface 的 spaces， [链接](https://huggingface.co/spaces/raynardj/modern-chinese-to-ancient-translate-wenyanwen)

版本
```
transformers==4.12.3
torch==1.7.1
```

```
PRETRAINED = "raynardj/wenyanwen-chinese-translate-to-ancient"
```
不是
```
PRETRAINED = r"wenyanwen-chinese-translate-to-ancient"
```
