### ISSUE TITLE
'BaseModelOutputWithPastAndCrossAttentions' object has no attribute 'logits'

### ISSUE THREAD

**Issue by liangtongt** [raynardj/yuan#2]
张老师，你好，在运行你的藏头诗项目时，报出错误，希望帮忙解答一下
`inference("上海",["高楼","虹光","灯红酒绿","华厦"])`
`[/usr/local/lib/python3.7/dist-packages/transformers/generation_utils.py](https://localhost:8080/#) in beam_sample(self, input_ids, beam_scorer, logits_processor, stopping_criteria, logits_warper, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, **model_kwargs)
   2298 
   2299             next_token_logits = outputs.logits[:, -1, :]
-> 2300 
   2301             # hack: adjust tokens for Marian. For Marian we have to make sure that the `pad_token_id`
   2302             # cannot be generated both before and after the `nn.functional.log_softmax` operation.

AttributeError: 'BaseModelOutputWithPastAndCrossAttentions' object has no attribute 'logits'`

**Comment by raynardj** [comment]
已修改， inference时不能用```AutoModel```应该用```AutoModelForCasualLM```
