### ISSUE TITLE
6W数据对跑完模型后推理生成空字符串

### ISSUE THREAD

**Issue by jiangliqin** [raynardj/yuan#4]
你好，我用日常-金庸风的文本对采用zh2cc_translate方法，decoder模块我采用one5ome/gpt2-chinese-gulong模型，跑完的模型encoder_decoder推理生成101:[UNK],batch_decode进行decoder得到空字符串。
请问是我的数据量太少了所以encoder_decoder generate是UNK吗？还是其他原因呢?

**Comment by raynardj** [comment]
不好意思，现在才看到。 @jiangliqin 

101应该说``batch decode``的tokenizer可能不认识字吧， 
* 照理说你可以decoder直接用一个正常的中文gpt2， 相应的tokenizer也是
* 拿你现在用的decoder直接encode target语句成token ids呢， 会看到很多101嘛？

---

觉得pair数据量少的话， 可以GPT2拿所有金庸文章先预训练， 就是你起头模型可以续写金庸的文章。 

如果你这么训练的话， 要踢掉序跋、三十三剑客图，和``飞狐外传`` ，因为那本虽续写``雪山飞狐``的前传， 但全文文风是散文体。

---

BTW你数据量是多少啊， 期待你的成果， 有意向的话我们可以合做一个huggingface.co space的小应用。

可以加我微信详细讨论``417848506``

**Comment by jiangliqin** [comment]
感谢您的耐心说明，我再尝试排查下问题，有进度我联系您
