### ISSUE TITLE
module.model in 断句

### ISSUE THREAD

**Issue by qtxwang** [raynardj/yuan#5]
Thanks for the great tool, I had fun playing with it. Where is module.model defined, what is the value?

ner = pipeline("ner",module.model,tokenizer=tokenizer)

**Comment by qtxwang** [comment]
OK I figured it out. Does it have some difficulty handling very long inputs?

Here is the example I tried:


"建隆元年春正月辛丑朔鎮定二州言北漢引契丹入冦周帝命歸徳軍節度使檢校太尉殿前都㸃檢趙匡領宿衛諸將禦之匡掌軍政六年士卒服其恩威數從世宗征伐洊立大功人望歸之至是王少國疑將士隂謀推戴壬寅殿前副都㸃檢鎮寧軍節度使太原慕容延釗將前軍先發癸卯大軍繼之軍中知星者河中苖訓見日下復有一日黒光摩盪者久之指謂匡親吏楚昭輔曰此天命也是夕次陳橋驛將士相與聚謀曰主上㓜弱我輩出死力破賊誰則知之不如先立㸃檢為天子然後北征都押衙李處耘具以其事白匡弟内殿祗候供奉官都知匡義【考異案王偁東都事畧陳桱通鑑續編作匡義薛氏王氏皆同惟李燾續通鑑長編楊仲良皇朝通鑑紀事本末作匡乂宋史太宗本紀亦云初名匡乂今姑從匡義】及歸徳節度掌書記薊人趙普【普初見顯徳三年二月】語未竟諸將露刄突入大言曰軍中定議欲册太尉為天子匡義普同聲叱之曰䇿立大事也固宜審圖且外冦壓境盍先攘之諸將不可曰事變未可知但當亟入京城䇿立太尉破賊不難也匡義因語諸將曰興王易姓雖云天命實繋人心汝等各能嚴飭軍士勿令剽刼都城人心安則四方自定汝等亦可共保富貴矣衆許諾乃共部分夜遣衙隊軍使郭延贇馳告殿前都指揮使石守信殿前都虞候王審【審初見徳三年】守信審琦皆素歸心匡者將士環列待旦匡醉卧初不省甲辰遲明諸將擐甲執兵直叩寢門曰諸軍無主願䇿太尉為天子匡驚起未及應即被以黄袍羅拜呼萬嵗掖乗馬南行匡度不得免乃攬轡誓諸將曰汝等自貪冨貴立我為天子能從吾命則可不然不能為若主也衆下馬曰唯命匡曰太后主上吾皆北面事之不得驚犯大臣皆我比肩不得侵凌朝廷府庫及士庶家不得攘掠用命有厚賞違不汝貰也皆應曰諾乃整軍自仁和門入秋毫無犯市不易肆乙巳入汴先遣客省使大名潘美見執政諭意又遣楚昭輔慰安家人時宰相方就食閤中聞變范質【質宗城人初見開運元年】執王溥【溥榆次人初見乾祐二年】手曰倉卒遣將吾輩之罪也爪入溥手幾出血溥噤不能對侍衛馬步軍副都指揮使太原韓通【通初見顯徳元年】自内庭惶遽奔歸將率衆備禦散員都指揮使王彦昇【彦昇初見顯徳三年】遇通於路躍馬逐之馳入其第殺通及其妻子【考異蘇轍龍川别志言韓通以親衛戰闕下敗死按通倉卒被殺未嘗交鋒今從續通鑑長編】諸將翼匡登明徳門匡令甲士還營退歸公署釋黄袍有頃諸將擁范質等至匡嗚咽流涕曰吾受世宗厚恩為六軍所迫一旦至此慙負天地將若之何質等未及對列校羅彦瓌按劔厲聲曰我輩無主今日須得天子質等相顧不知所為王溥降階先拜質不得已亦拜【考異司馬光記聞云質頗誚讓太祖王偁東都事畧范質傳既見太祖質曰先帝養太尉如子今身未冷奈何陳桱通鑑續編云范質以義讓匡薛應旂宋元通鑑亦載質讓匡曰先帝養大尉如子今骨肉未寒而太尉若此奈先帝何按王溥降階拜質亦從之拜安肯侃侃以大義責宋祖乎長編及宋史並無此語今不取】質曰古有禪讓之禮今可行也因具陳之遂請匡詣崇元殿行禪代禮召文武百僚至晡班定翰林學士承㫖新平陶穀【糓初見乾祐元年】袖中出周帝禪詔【詔曰天生烝民樹之司牧二帝惟公而禪位三王乗時而革命其揆一也予末小子遭家不造人心已去天命有歸咨爾歸徳軍節度使殿前都㸃檢趙匡禀上聖之姿有神武之畧佐我高祖格于皇天逮事世宗功存納麓東征西怨厥績懋焉天地神享於有徳謳歌獄訟歸於至仁應天順人法堯禪舜如釋重負子其作賔嗚呼欽哉祗畏天命】宣徽使引匡就龍墀北面拜受【宋史及實録並無宣徽使姓名疑即昝居潤也】宰相掖并崇元殿服衮冕即皇帝位羣臣拜賀奉周帝為鄭王符太后為周太后遷居西宫【考異龍川别志言太祖脫甲詣政事堂范質見大祖首陳禪代議又東都事畧范質傳質曰大尉既以禮受嬗則事太后如母養少主如子與飛龍記司馬光記聞朔記等所載都不同按太祖實歸府第將士即擁范質等至質等見太祖必不在政事堂其約束將士不得加無禮於太后少帝固先定于未入城時非縁質請也惟執王溥手出血及光所記質不肯先拜當得其實】乙巳詔定有天下之號曰宋【因所領節度州名也】改元大赦内外馬步軍士等第優給命官分告天地社稷遣中使齎詔諭天下其諸道節度使别以詔賜焉華山隠士陳摶聞帝代周曰天下自此定矣"

建隆元年春正月辛丑朔，鎮。定二州言北漢引契丹入冦。周帝命歸徳軍節度使。檢校太尉。殿前都㸃檢趙匡領宿衛諸將禦之。匡掌軍政六年，士卒服其恩威，數從世宗征伐，洊立大功，人望歸之。至是，王少國疑將士隂謀推戴。壬寅，殿前副都㸃檢。鎮寧軍節度使太原慕容延釗將前軍先發。癸卯，大軍繼之。軍中知星者河中苖訓見日下復有一日，黒光摩盪者久之，指謂匡親吏楚昭輔曰"此天命也。是夕，次陳橋驛，將士相與聚謀曰"主上㓜弱，我輩出死力破賊，誰則知之？不如先立㸃檢為天子，然後北征。都押衙李處耘具以其事白匡弟内殿祗候供奉官都知匡義【考異。案：王偁東都事畧陳桱通鑑續編作匡義。薛氏。王氏皆同。惟李燾續通鑑長編楊仲良【皇朝通鑑紀事本末作匡乂【宋史太宗本紀】亦云"初名匡乂，今姑從匡義】。及歸徳節度掌書記薊人趙普【普初見顯徳三年二月】。語未竟，諸將露刄突入，大言曰"軍中定議，欲册太尉為天子。匡義。普同聲叱之曰"䇿立大事也，固宜審圖。且外冦壓境，盍先攘之，諸將不可，曰"事變未可知，但當亟入京城，䇿立太尉，破賊不難也。匡義因語諸將曰"興王易姓，雖云天命，實繋人心，汝等各能嚴飭軍士，勿令剽刼都城，人心安，則四方自定，汝等亦可共保富貴矣！衆許諾，乃共部分夜遣衙隊軍使郭延贇馳告殿前都指揮使石守信。殿前都虞候王審【審初見徳三年】。守信審琦皆素歸心。匡者，將士環列待旦，匡醉卧，初不省。甲辰遲明，諸將擐甲執兵直叩寢門曰"諸軍無主願䇿太尉為天子匡驚起未及應即被以黄袍羅拜呼萬嵗掖乗馬南行匡度不得免乃攬轡誓諸將曰汝等自貪冨貴立我為天子能從吾命則可不然不能為若主也衆下馬曰唯命匡曰太后主上吾皆北面事之不得驚犯大臣皆我比肩不得侵凌朝廷府庫及士庶家不得攘掠用命有厚賞違不汝貰也皆應曰諾乃整軍自仁和門入秋毫無犯市不易肆乙巳入汴先遣客省使大名潘美見執政諭意又遣楚昭輔慰安家人時宰相方就食閤中聞變范質【質宗城人初見開運元年】執王溥【溥榆次人初見乾祐二年】手曰倉卒遣將吾輩之罪也爪入溥手幾出血溥噤不能對侍衛馬步軍副都指揮使太原韓通【通初見顯徳元年】自内庭惶遽奔歸將率衆備禦散員都指揮使王彦昇【彦昇初見顯徳三年】遇通於路躍馬逐之馳入其第殺通及其妻子【考異蘇轍龍川别志言韓通以親衛戰闕下敗死按通倉卒被殺未嘗交鋒今從續通鑑長編】諸將翼匡登明徳門匡令甲士還營退歸公署釋黄袍有頃諸將擁范質等至匡嗚咽流涕曰吾受世宗厚恩為六軍所迫一旦至此慙負天地將若之何質等未及對列校羅彦瓌按劔厲聲曰我輩無主今日須得天子質等相顧不知所為王溥降階先拜質不得已亦拜【考異司馬光記聞云質頗誚讓太祖王偁東都事畧范質傳既見太祖質曰先帝養太尉如子今身未冷奈何陳桱通鑑續編云范質以義讓匡薛應旂宋元通鑑亦載質讓匡曰先帝養大尉如子今骨肉未寒而太尉若此奈先帝何按王溥降階拜質亦從之拜安肯侃侃以大義責宋祖乎長編及宋史並無此語今不取】質曰古有禪讓之禮今可行也因具陳之遂請匡詣崇元殿行禪代禮召文武百僚至晡班定翰林學士承㫖新平陶穀【糓初見乾祐元年】袖中出周帝禪詔【詔曰天生烝民樹之司牧二帝惟公而禪位三王乗時而革命其揆一也予末小子遭家不造人心已去天命有歸咨爾歸徳軍節度使殿前都㸃檢趙匡禀上聖之姿有神武之畧佐我高祖格于皇天逮事世宗功存納麓東征西怨厥績懋焉天地神享於有徳謳歌獄訟歸於至仁應天順人法堯禪舜如釋重負子其作賔嗚呼欽哉祗畏天命】宣徽使引匡就龍墀北面拜受【宋史及實録並無宣徽使姓名疑即昝居潤也】宰相掖并崇元殿服衮冕即皇帝位羣臣拜賀奉周帝為鄭王符太后為周太后遷居西宫【考異龍川别志言太祖脫甲詣政事堂范質見大祖首陳禪代議又東都事畧范質傳質曰大尉既以禮受嬗則事太后如母養少主如子與飛龍記司馬光記聞朔記等所載都不同按太祖實歸府第將士即擁范質等至質等見太祖必不在政事堂其約束將士不得加無禮於太后少帝固先定于未入城時非縁質請也惟執王溥手出血及光所記質不肯先拜當得其實】乙巳詔定有天下之號曰宋【因所領節度州名也】改元大赦内外馬步軍士等第優給命官分告天地社稷遣中使齎詔諭天下其諸道節度使别以詔賜焉華山隠士陳摶聞帝代周曰天下自此定矣

**Comment by raynardj** [comment]
@qtxwang  感谢关注这个项目。

这个模型当初训练的时候， 是拿一个爬取殆知阁的数据集做的。 比如[这个页面](http://www.daizhige.org/%E8%AF%97%E8%97%8F/%E8%AF%8D%E8%AF%9D/%E6%88%8F%E9%B8%A5%E5%B1%85%E8%AF%8D%E8%AF%9D.html). （殆知阁是一个整理得很干净的古文网站。）

然后我判别了下有标点的文章， 把标点去了作为X， 有标点的原文作为Y 这么训练出来的。

但是呢。。。 殆知阁大多数文章是**简体字**的， 繁体字虽然模型也能跑通，但大多数繁体的token embedding weights没有经过断句任务的finetune， 推测繁体字文章会有点漏。

如有改进或者提升的方案，也欢迎直接PR添加到nbs笔记里

**Comment by qtxwang** [comment]
Thanks for sharing the training method. I think it worked fine in the first half, the second half it just stopped working. Maybe it is not the model itself but how the model was applied?

**Comment by raynardj** [comment]
@qtxwang **SIMPLIFIED** Chinese, please use **SIMPLIFIED** Chinese

**Comment by lixucuhk** [comment]
> OK I figured it out. Does it have some difficulty handling very long inputs?
> 
> Here is the example I tried:
> 
> "建隆元年春正月辛丑朔鎮定二州言北漢引契丹入冦周帝命歸徳軍節度使檢校太尉殿前都㸃檢趙匡領宿衛諸將禦之匡掌軍政六年士卒服其恩威數從世宗征伐洊立大功人望歸之至是王少國疑將士隂謀推戴壬寅殿前副都㸃檢鎮寧軍節度使太原慕容延釗將前軍先發癸卯大軍繼之軍中知星者河中苖訓見日下復有一日黒光摩盪者久之指謂匡親吏楚昭輔曰此天命也是夕次陳橋驛將士相與聚謀曰主上㓜弱我輩出死力破賊誰則知之不如先立㸃檢為天子然後北征都押衙李處耘具以其事白匡弟内殿祗候供奉官都知匡義【考異案王偁東都事畧陳桱通鑑續編作匡義薛氏王氏皆同惟李燾續通鑑長編楊仲良皇朝通鑑紀事本末作匡乂宋史太宗本紀亦云初名匡乂今姑從匡義】及歸徳節度掌書記薊人趙普【普初見顯徳三年二月】語未竟諸將露刄突入大言曰軍中定議欲册太尉為天子匡義普同聲叱之曰䇿立大事也固宜審圖且外冦壓境盍先攘之諸將不可曰事變未可知但當亟入京城䇿立太尉破賊不難也匡義因語諸將曰興王易姓雖云天命實繋人心汝等各能嚴飭軍士勿令剽刼都城人心安則四方自定汝等亦可共保富貴矣衆許諾乃共部分夜遣衙隊軍使郭延贇馳告殿前都指揮使石守信殿前都虞候王審【審初見徳三年】守信審琦皆素歸心匡者將士環列待旦匡醉卧初不省甲辰遲明諸將擐甲執兵直叩寢門曰諸軍無主願䇿太尉為天子匡驚起未及應即被以黄袍羅拜呼萬嵗掖乗馬南行匡度不得免乃攬轡誓諸將曰汝等自貪冨貴立我為天子能從吾命則可不然不能為若主也衆下馬曰唯命匡曰太后主上吾皆北面事之不得驚犯大臣皆我比肩不得侵凌朝廷府庫及士庶家不得攘掠用命有厚賞違不汝貰也皆應曰諾乃整軍自仁和門入秋毫無犯市不易肆乙巳入汴先遣客省使大名潘美見執政諭意又遣楚昭輔慰安家人時宰相方就食閤中聞變范質【質宗城人初見開運元年】執王溥【溥榆次人初見乾祐二年】手曰倉卒遣將吾輩之罪也爪入溥手幾出血溥噤不能對侍衛馬步軍副都指揮使太原韓通【通初見顯徳元年】自内庭惶遽奔歸將率衆備禦散員都指揮使王彦昇【彦昇初見顯徳三年】遇通於路躍馬逐之馳入其第殺通及其妻子【考異蘇轍龍川别志言韓通以親衛戰闕下敗死按通倉卒被殺未嘗交鋒今從續通鑑長編】諸將翼匡登明徳門匡令甲士還營退歸公署釋黄袍有頃諸將擁范質等至匡嗚咽流涕曰吾受世宗厚恩為六軍所迫一旦至此慙負天地將若之何質等未及對列校羅彦瓌按劔厲聲曰我輩無主今日須得天子質等相顧不知所為王溥降階先拜質不得已亦拜【考異司馬光記聞云質頗誚讓太祖王偁東都事畧范質傳既見太祖質曰先帝養太尉如子今身未冷奈何陳桱通鑑續編云范質以義讓匡薛應旂宋元通鑑亦載質讓匡曰先帝養大尉如子今骨肉未寒而太尉若此奈先帝何按王溥降階拜質亦從之拜安肯侃侃以大義責宋祖乎長編及宋史並無此語今不取】質曰古有禪讓之禮今可行也因具陳之遂請匡詣崇元殿行禪代禮召文武百僚至晡班定翰林學士承㫖新平陶穀【糓初見乾祐元年】袖中出周帝禪詔【詔曰天生烝民樹之司牧二帝惟公而禪位三王乗時而革命其揆一也予末小子遭家不造人心已去天命有歸咨爾歸徳軍節度使殿前都㸃檢趙匡禀上聖之姿有神武之畧佐我高祖格于皇天逮事世宗功存納麓東征西怨厥績懋焉天地神享於有徳謳歌獄訟歸於至仁應天順人法堯禪舜如釋重負子其作賔嗚呼欽哉祗畏天命】宣徽使引匡就龍墀北面拜受【宋史及實録並無宣徽使姓名疑即昝居潤也】宰相掖并崇元殿服衮冕即皇帝位羣臣拜賀奉周帝為鄭王符太后為周太后遷居西宫【考異龍川别志言太祖脫甲詣政事堂范質見大祖首陳禪代議又東都事畧范質傳質曰大尉既以禮受嬗則事太后如母養少主如子與飛龍記司馬光記聞朔記等所載都不同按太祖實歸府第將士即擁范質等至質等見太祖必不在政事堂其約束將士不得加無禮於太后少帝固先定于未入城時非縁質請也惟執王溥手出血及光所記質不肯先拜當得其實】乙巳詔定有天下之號曰宋【因所領節度州名也】改元大赦内外馬步軍士等第優給命官分告天地社稷遣中使齎詔諭天下其諸道節度使别以詔賜焉華山隠士陳摶聞帝代周曰天下自此定矣"
> 
> 建隆元年春正月辛丑朔，鎮。定二州言北漢引契丹入冦。周帝命歸徳軍節度使。檢校太尉。殿前都㸃檢趙匡領宿衛諸將禦之。匡掌軍政六年，士卒服其恩威，數從世宗征伐，洊立大功，人望歸之。至是，王少國疑將士隂謀推戴。壬寅，殿前副都㸃檢。鎮寧軍節度使太原慕容延釗將前軍先發。癸卯，大軍繼之。軍中知星者河中苖訓見日下復有一日，黒光摩盪者久之，指謂匡親吏楚昭輔曰"此天命也。是夕，次陳橋驛，將士相與聚謀曰"主上㓜弱，我輩出死力破賊，誰則知之？不如先立㸃檢為天子，然後北征。都押衙李處耘具以其事白匡弟内殿祗候供奉官都知匡義【考異。案：王偁東都事畧陳桱通鑑續編作匡義。薛氏。王氏皆同。惟李燾續通鑑長編楊仲良【皇朝通鑑紀事本末作匡乂【宋史太宗本紀】亦云"初名匡乂，今姑從匡義】。及歸徳節度掌書記薊人趙普【普初見顯徳三年二月】。語未竟，諸將露刄突入，大言曰"軍中定議，欲册太尉為天子。匡義。普同聲叱之曰"䇿立大事也，固宜審圖。且外冦壓境，盍先攘之，諸將不可，曰"事變未可知，但當亟入京城，䇿立太尉，破賊不難也。匡義因語諸將曰"興王易姓，雖云天命，實繋人心，汝等各能嚴飭軍士，勿令剽刼都城，人心安，則四方自定，汝等亦可共保富貴矣！衆許諾，乃共部分夜遣衙隊軍使郭延贇馳告殿前都指揮使石守信。殿前都虞候王審【審初見徳三年】。守信審琦皆素歸心。匡者，將士環列待旦，匡醉卧，初不省。甲辰遲明，諸將擐甲執兵直叩寢門曰"諸軍無主願䇿太尉為天子匡驚起未及應即被以黄袍羅拜呼萬嵗掖乗馬南行匡度不得免乃攬轡誓諸將曰汝等自貪冨貴立我為天子能從吾命則可不然不能為若主也衆下馬曰唯命匡曰太后主上吾皆北面事之不得驚犯大臣皆我比肩不得侵凌朝廷府庫及士庶家不得攘掠用命有厚賞違不汝貰也皆應曰諾乃整軍自仁和門入秋毫無犯市不易肆乙巳入汴先遣客省使大名潘美見執政諭意又遣楚昭輔慰安家人時宰相方就食閤中聞變范質【質宗城人初見開運元年】執王溥【溥榆次人初見乾祐二年】手曰倉卒遣將吾輩之罪也爪入溥手幾出血溥噤不能對侍衛馬步軍副都指揮使太原韓通【通初見顯徳元年】自内庭惶遽奔歸將率衆備禦散員都指揮使王彦昇【彦昇初見顯徳三年】遇通於路躍馬逐之馳入其第殺通及其妻子【考異蘇轍龍川别志言韓通以親衛戰闕下敗死按通倉卒被殺未嘗交鋒今從續通鑑長編】諸將翼匡登明徳門匡令甲士還營退歸公署釋黄袍有頃諸將擁范質等至匡嗚咽流涕曰吾受世宗厚恩為六軍所迫一旦至此慙負天地將若之何質等未及對列校羅彦瓌按劔厲聲曰我輩無主今日須得天子質等相顧不知所為王溥降階先拜質不得已亦拜【考異司馬光記聞云質頗誚讓太祖王偁東都事畧范質傳既見太祖質曰先帝養太尉如子今身未冷奈何陳桱通鑑續編云范質以義讓匡薛應旂宋元通鑑亦載質讓匡曰先帝養大尉如子今骨肉未寒而太尉若此奈先帝何按王溥降階拜質亦從之拜安肯侃侃以大義責宋祖乎長編及宋史並無此語今不取】質曰古有禪讓之禮今可行也因具陳之遂請匡詣崇元殿行禪代禮召文武百僚至晡班定翰林學士承㫖新平陶穀【糓初見乾祐元年】袖中出周帝禪詔【詔曰天生烝民樹之司牧二帝惟公而禪位三王乗時而革命其揆一也予末小子遭家不造人心已去天命有歸咨爾歸徳軍節度使殿前都㸃檢趙匡禀上聖之姿有神武之畧佐我高祖格于皇天逮事世宗功存納麓東征西怨厥績懋焉天地神享於有徳謳歌獄訟歸於至仁應天順人法堯禪舜如釋重負子其作賔嗚呼欽哉祗畏天命】宣徽使引匡就龍墀北面拜受【宋史及實録並無宣徽使姓名疑即昝居潤也】宰相掖并崇元殿服衮冕即皇帝位羣臣拜賀奉周帝為鄭王符太后為周太后遷居西宫【考異龍川别志言太祖脫甲詣政事堂范質見大祖首陳禪代議又東都事畧范質傳質曰大尉既以禮受嬗則事太后如母養少主如子與飛龍記司馬光記聞朔記等所載都不同按太祖實歸府第將士即擁范質等至質等見太祖必不在政事堂其約束將士不得加無禮於太后少帝固先定于未入城時非縁質請也惟執王溥手出血及光所記質不肯先拜當得其實】乙巳詔定有天下之號曰宋【因所領節度州名也】改元大赦内外馬步軍士等第優給命官分告天地社稷遣中使齎詔諭天下其諸道節度使别以詔賜焉華山隠士陳摶聞帝代周曰天下自此定矣

I met the same problem on the "module.model" issue. Could you please tell me how you figure it out? Many thanks!
